# Laboratory 4

### Imports

In [2]:
import numpy as np

### Task 1

დაწერეთ პროგრამა რომლის მეშვებით შეიტანთ ნებისმიერ სტრიქონს (input ბრძანების გამოყენებით). დაბეჭდეთ შეყვანილი სტრიოქნის სიგრძე (სიმბოლოების რაოდენობა).

In [118]:
s = input("შეიყვანეთ სტრიქონი: ")
print(len(s))

18


### Task 2

შეიყვანეთ ნებისმიერი ორი სტრიქონი. ახალ ცვლადში მოახდინეთ მათი შეერთება და დაბეჭდეთ შედეგი.

In [119]:
s1 = input("შეიყვანეთ სტრიქონი: ")
s2 = input("შეიყვანეთ სტრიქონი: ")
s3 = s1 + " " + s2
print(s3)

asdf asdf sda f asdfpwoieurw er


### Task 3

შეიყვანეთ სტრიქონი. დაითვალეთ რამდენჯერ შეგხვდათ სიმბოლო “a” დაბეჭდეთ შედეგი.

In [120]:
s = input("შეიყვანეთ სტრიქონი: ")
print(s.count('a'))

7


### Task 5

text ცვლადს მიანიჭეთ სტრიქონი “სწავლის ძირი მწარე არის, კენწეროში გატკბილდების”. სტრიქონიდან წაიკითხეთ პირველი 20 სიმბოლო და დაბეჭდეთ შედეგი. დაითვალეთ რამდენჯერ არის ნახსენები სიმბოლო ‘ს’.

In [121]:
text = "სწავლის ძირი მწარე არის, კენწეროში გატკბილდების"
print(text[:20])
print(text.count('ს'))

სწავლის ძირი მწარე ა
4


### Task 11

text ცვლადს მიანიჭეთ შემდეგი ტექსტი: “Have a nice day”. დაბეჭდეთ ტექსტის თითოეული სიმბოლო ეკრანზე უკუ მიმართულებით ცალ-ცალკე ხაზზე (ანუ პირველად დაბეჭდავ ბოლო სიმბოლოს, შემდეგ ბოლოს წინა სიმბოლოს, და ა.შ).

In [125]:
text = "Have a nice day"
for i in range(len(text)-1, 0, -1):
    print(text[i])

y
a
d
 
e
c
i
n
 
a
 
e
v
a


### Task 13

დაწერეთ პროგრამა, სადაც user შეიყვანს თავის სახელს და გვარს და პროგრამა დაუბეჭდავს შესაბამის იმეილის დასახელებას: მაგ: adam.giorgadze@edu.ge

In [126]:
firstname = input("სახელი: ")
lastname = input("გვარი: ")
print(f"{firstname}.{lastname}@gau.edu.ge")

sdf.sdfsdf@gau.edu.ge


### Task 15

მოახდინეთ ორი მატრიცის შეკრების მოდელირება. მოიყვანეთ ორი მაგალითი
(შემთხვევითი და სტატიკური რიცხვებისთვის)

In [5]:
m1 = np.random.randint(1, 100, size=(3, 3))
m2 = np.array([[10, 5, 12], [5, 10, 5], [2, 5, 90]]) 
print(m1+m2)

[[ 61  25  94]
 [ 80 106 104]
 [ 24  92 114]]


### Task 17

მოახდინეთ ორი მატრიცის გამრავლების მოდელირება. მოიყვანეთ ორი მაგალითი (შემთხვევითი და სტატიკური რიცხვებისთვის)

In [8]:
m1_rand = np.random.randint(1, 100, size=(4, 4))
m2_rand = np.random.randint(1, 100, size=(4, 4))
print("შემთხვევითი: ")
print(m1_rand.dot(m2_rand))

print("სტატიკური: ")
m1_static = np.array([[1, 2, 3, 4] , [5, 6, 7 , 8], [9, 10, 11, 12], [13, 14, 15, 16]])
m2_static = np.array([[11, 9, 7, 4] , [5, 9, 0 , 8], [8, 13, 21, 2], [1, 4, 45, 26]])
print(m1_static.dot(m2_static))

შემთხვევითი: 
[[13740 16700 10875 13255]
 [ 8403  9284  8810  8815]
 [ 8586 15726 10523 10259]
 [ 9617  9482  3214 10435]]
სტატიკური: 
[[  49   82  250  130]
 [ 149  222  542  290]
 [ 249  362  834  450]
 [ 349  502 1126  610]]


### Task 19

შეავსეთ 10x10 მატრიცა შემთხვევითი რიცხვებით [0, 10] შუალედიდან. წაშალეთ კლავიატურიდან შეტანილი რიცხვი. გამოიყენეთ numpy ბიბლიოთეკა.

In [40]:
m = np.random.randint(0, 11, size=(10, 10))
num = int(input("შეიყვანე რიცხვი: "))
m = np.delete(m, num) # deletes and flattens array into 1D

print(m)

[ 4  6  0  0  4  3  6  4  4  2  4  7  9  1  0  6  5  0 10 10  7  2  1  2
  0  1  2  6  5  4  3  1  0  5  2  5  9  9 10  9 10  4  3  0  1  1  8  2
  5  4  7 10 10  2  3  3  8  2 10  4  4  8  4  3  5  9  7  4  4  6  9  4
  0  6  6  4  9 10  0  8  7  6  0  0  4  3  4  1  0  2  9  7  0  9  0  4
  9  2  8]


### Task 20

შეავსეთ 10x10 მატრიცა შემთხვევითი რიცხვებით [0, 10] შუალედიდან. წაშალეთ კლავიატურიდან შეტანილი სვეტი. გამოიყენეთ numpy ბიბლიოთეკა.

In [102]:
m = np.random.randint(0, 11, size=(10, 10))
num = int(input("შეიყვანე რიცხვი: "))
m = np.delete(m, num, axis=1)

print(m)

[[ 8  9  7  2  5  3  7  1  8]
 [ 1  3  7  4  4  5  7 10  1]
 [ 2  7  6  9  7  4  5  5  5]
 [ 9  8  6  3  4  0  6  4  3]
 [10 10  6  1  1  4  5  0  1]
 [ 0  7  6  2  5  9  8  1 10]
 [ 1 10  1  4  8  4  6  1  2]
 [ 5  8  1  3  3  5  3  1  5]
 [ 5  2  8 10 10  4  4  6  2]
 [ 6  0  2  1  3  1  5  9  7]]


### Task 21

შეავსეთ 10x10 მატრიცა შემთხვევითი რიცხვებით [0, 10] შუალედიდან. შეცვალეთ ყველა 0-ის მნიშვნელობა 1-ით. გამოიყენეთ numpy ბიბლიოთეკა.

In [117]:
m = np.random.randint(0, 11, size=(10, 10))
print(0 in m)
m[m==0] = 1
print(0 in m)

True
False


### Task 22

ააგეთ ჭადრაკის დაფა. გამოიყენეთ numpy ბიბლიოთეკა.

In [93]:
board = np.zeros(shape=(8, 8), dtype="int")
board[1::2, ::2] = 1
board[::2, 1::2] = 1
print(board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Task 23

შეავსეთ ორი 10x10 მატრიცა შემთხვევითი რიცხვებით [0, 10] შუალედიდან. გადაიყვანეთ ორივე მატრიცა ერთ ლისტად. გამოიყენეთ numpy ბიბლიოთეკა.

In [101]:
m1 = np.random.randint(0, 11, size=(10, 10))
m2 = np.random.randint(0, 11, size=(10, 10))
print(np.concatenate((m1, m2), axis=0).flatten().tolist())

[0, 10, 1, 1, 6, 10, 8, 6, 1, 9, 9, 9, 3, 6, 2, 5, 6, 2, 7, 0, 2, 5, 4, 4, 1, 6, 1, 0, 0, 9, 1, 2, 0, 2, 2, 8, 3, 9, 5, 4, 0, 1, 4, 10, 8, 3, 3, 6, 1, 0, 7, 4, 9, 4, 4, 7, 4, 7, 6, 7, 6, 3, 10, 10, 5, 8, 4, 9, 2, 0, 7, 5, 8, 0, 7, 5, 1, 1, 10, 1, 2, 8, 6, 1, 5, 7, 2, 3, 8, 10, 0, 1, 9, 2, 5, 9, 4, 1, 8, 3, 0, 8, 1, 1, 0, 9, 10, 1, 1, 7, 6, 9, 1, 10, 10, 3, 7, 8, 6, 0, 5, 5, 9, 0, 5, 3, 8, 4, 1, 1, 0, 6, 8, 8, 5, 7, 7, 7, 10, 10, 5, 6, 0, 5, 9, 1, 9, 0, 2, 10, 10, 0, 5, 6, 3, 7, 1, 2, 9, 8, 8, 1, 1, 1, 6, 1, 1, 8, 8, 10, 3, 5, 1, 1, 4, 5, 8, 8, 0, 8, 7, 0, 9, 5, 9, 6, 3, 5, 9, 7, 2, 3, 0, 6, 5, 5, 0, 0, 4, 10]
