# Laboratory 7

### Imports

In [2]:
import numpy as np

### Task 1

განსაზღვრეთ 36 ელემენტიანი შემთხვევით [0, 100] შუალედიდან მთელ რიცხვთა 1 განზომილებიანი, 2 განზომილებიანი და 3 განზომილებიანი numpy მასივები და დაბეჭდეთ.

In [17]:
m1 = np.random.randint(0, 101, size=36)
m2 = np.random.randint(0, 101, size=(6, 6))
m3 = np.random.randint(0, 101, size=(6, 3, 2))

print(m1)
print(m2)
print(m3)

[ 21  44   0  50  39  16  23  56  61  52  74  26  68  91  18  96  72  28
  53  49  39  60  76  58  21  35  73  33  20  83  18 100  41  62  83  50]
[[94 56 40 83 55 73]
 [34 88 56 73 25 94]
 [28 70 24 40  2 38]
 [41 66 31 19 59 18]
 [44 98 81 66 66  2]
 [ 6 37 71 48 31  7]]
[[[46 17]
  [74 83]
  [81 76]]

 [[38 14]
  [99 97]
  [38 60]]

 [[17 49]
  [61 47]
  [98 52]]

 [[35 76]
  [57  2]
  [55 12]]

 [[67 84]
  [71 91]
  [56 95]]

 [[47  0]
  [91 24]
  [13 54]]]


### Task 2

განსაზღვრეთ 36 ელემენტიანი შემთხვევით [0, 100] შუალედიდან მთელ რიცხვთა 1 განზომილებიანი მასივი, გადაიყვანეთ ყველა შესაძლო 2 განზომილებიან, 3 განზომილებიან მასივად და დაბეჭდეთ. 

In [44]:
def find_factors(n: int) -> np.ndarray:
    divisors = np.array([], dtype=int)
    i = 2
    while i <= np.sqrt(n):
        if (n % i == 0):
            if (n / i == i):
                divisors = np.append(divisors,i)
            else :
                divisors = np.append(divisors, i)
                divisors = np.append(divisors, int(n/i))
        i+=1
    return divisors


m = np.random.randint(0, 101, size=36)

# all possible 2d arrays from m
# {possible dimention: 2d array}
d2 = {}
for d in find_factors(len(m)):
    c = m.reshape(d, int(len(m)/d))
    d2[f"{d}x{int(len(m)/d)}"] = c


# all possible 3d arrays from m
# {possible dimention: 3darray}
d3 = {}


{'2x18': array([[ 95,  38,  81,  83,  44,  17,  17,  37,  17, 100,  22,  22, 100,
         53,  55,  43,  15,  95],
       [ 49,  92,  71,  70,  48,  73,   4,  97,  38,  29,  59,  12,  68,
         10,  23,  82,  85,  72]]), '18x2': array([[ 95,  38],
       [ 81,  83],
       [ 44,  17],
       [ 17,  37],
       [ 17, 100],
       [ 22,  22],
       [100,  53],
       [ 55,  43],
       [ 15,  95],
       [ 49,  92],
       [ 71,  70],
       [ 48,  73],
       [  4,  97],
       [ 38,  29],
       [ 59,  12],
       [ 68,  10],
       [ 23,  82],
       [ 85,  72]]), '3x12': array([[ 95,  38,  81,  83,  44,  17,  17,  37,  17, 100,  22,  22],
       [100,  53,  55,  43,  15,  95,  49,  92,  71,  70,  48,  73],
       [  4,  97,  38,  29,  59,  12,  68,  10,  23,  82,  85,  72]]), '12x3': array([[ 95,  38,  81],
       [ 83,  44,  17],
       [ 17,  37,  17],
       [100,  22,  22],
       [100,  53,  55],
       [ 43,  15,  95],
       [ 49,  92,  71],
       [ 70,  48,  73],
      

### Task 3

numpy-ის საშუალებით ააგეთ მიმატება, გამოკლება, გამრავლება, გაყოფის ოპერაციები ორ რიცხვზე. 

In [45]:
n1 = int(input("Number 1: "))
n2 = int(input("Number 2: "))

print(f"{n1}+{n2} = {np.add(n1, n2)}")
print(f"{n1}-{n2} = {np.subtract(n1, n2)}")
print(f"{n1}x{n2} = {np.multiply(n1, n2)}")
print(f"{n1}/{n2} = {np.divide(n1, n2)}")

1+3 = 4
1-3 = -2
1x3 = 3
1/3 = 0.3333333333333333


### Task 4

განსაზღვრეთ 36 ელემენტიანი შემთხვევით [0, 100] შუალედიდან მთელ რიცხვთა 1 განზომილებიანი a მასივი, numpy-ის საშუალებით ააგეთ ახალი მასივი, რომელშიდაც შეინახავთ a მასივის ყოველ ელემენტის განაყოფს კლავიატურიდან შეტანილი რიცხვზე. ააგეთ ახალი მასივი, რომელშიდაც შეინახავთ a მასივის ყოველ ელემენტის მთელ განაყოფს კლავიატურიდან შეტანილი რიცხვზე.

In [49]:
a = np.random.randint(0, 101, size=36)
n = int(input("Enter number: "))
print(a/n)
print()
print(a//n)

[29.         25.33333333 13.33333333 10.33333333 22.33333333 18.33333333
  5.33333333  2.66666667  3.         29.33333333  8.66666667  6.
 13.          6.         11.33333333 12.66666667 13.66666667 32.66666667
 16.         22.         24.66666667 14.33333333 10.66666667 26.66666667
 29.66666667  0.         15.33333333 27.33333333 17.66666667 21.
 25.66666667 17.          4.66666667  4.66666667 20.         26.        ]

[29 25 13 10 22 18  5  2  3 29  8  6 13  6 11 12 13 32 16 22 24 14 10 26
 29  0 15 27 17 21 25 17  4  4 20 26]


### Task 5

განსაზღვრეთ 5x3 და 3x2-ზე მასივები, რომლებიც შეავსეთ შემთხვევითი მთელი რიცხვებით [0, 100] შუალედიდან, იპოვეთ პირველის მეორეზე ნამრავლი. 

In [50]:
m1 = np.random.randint(0, 101, size=(5, 3))
m2 = np.random.randint(0, 101, size=(3, 2))

print(m1.dot(m2))

[[ 7084  6974]
 [ 7649 12346]
 [ 5315  6386]
 [ 8246 12014]
 [15822 13716]]


### Task 6

განსაზღვრეთ 6, 9 და 12 ელემენტიანი შემთხვევით [0, 100] შუალედიდან numpy მასივები და გააერთიანეთ. 

In [75]:
n = np.concatenate((
    np.random.randint(0, 101, size=6),
    np.random.randint(0, 101, size=9),
    np.random.randint(0, 101, size=12)
))

print(n)

[13 29 21 28 25 96 91 60 67 84 56 26 94 38  8  4 35 20 14 46  8 17 33 84
 42  2 89]
27


### Task 7

განსაზღვრეთ ორი 12 ელემენტიანი შემთხვევით [0, 100] შუალედიდან numpy მასივები, იპოვეთ შიდა, გარე და ჯვარედინი ნამრავლი. 

In [93]:
a1 = np.random.randint(0, 100, size=12)
a2 = np.random.randint(0, 100, size=12)

print(a1)
print(a2)
print()
print(np.inner(a1, a2))
print(np.outer(a1, a2))
# print(np.cross(a1, a2))

[32 97 75 48 61 51  7 14 58 72 76 33]
[35 54 92 99 15  9 46  4 57 44  0 43]

27655
[[1120 1728 2944 3168  480  288 1472  128 1824 1408    0 1376]
 [3395 5238 8924 9603 1455  873 4462  388 5529 4268    0 4171]
 [2625 4050 6900 7425 1125  675 3450  300 4275 3300    0 3225]
 [1680 2592 4416 4752  720  432 2208  192 2736 2112    0 2064]
 [2135 3294 5612 6039  915  549 2806  244 3477 2684    0 2623]
 [1785 2754 4692 5049  765  459 2346  204 2907 2244    0 2193]
 [ 245  378  644  693  105   63  322   28  399  308    0  301]
 [ 490  756 1288 1386  210  126  644   56  798  616    0  602]
 [2030 3132 5336 5742  870  522 2668  232 3306 2552    0 2494]
 [2520 3888 6624 7128 1080  648 3312  288 4104 3168    0 3096]
 [2660 4104 6992 7524 1140  684 3496  304 4332 3344    0 3268]
 [1155 1782 3036 3267  495  297 1518  132 1881 1452    0 1419]]


### Task 8

numpy-ის საშუალებით იპოვეთ შემდეგი მრავალწევრის ფესვები x^2+4x-5;  x^4-2x^3+x^2-4x-5. 

In [108]:
print(np.roots([1, 4, -5]))
print(np.roots([1, -2, 1, -4, -5]))

[-5.  1.]
[ 2.53494103+0.j          0.12037678+1.59006434j  0.12037678-1.59006434j
 -0.77569459+0.j        ]


### Task 9

numpy-ის საშუალებით იპოვეთ კლავიატურიდან შეტანილი სტრიქონის შესაბამისად მრავალწევრის ფესვები. 

In [151]:
coeff = []
equation = input("Enter equation: ").replace(" ", "")
equation = equation.replace("+", " +").replace("-", " -")
print(equation)

for p in equation.split():
    n = p.split('x')[0]
    if n == '':
        coeff.append(1)
    elif n[0] == '-':
        if len(n[0]) == 1:
            coeff.append(-1)
        else:
            coeff.append(int(n.removeprefix("-"))*-1)
    elif n[0] == '+':
        coeff.append(int(n.removeprefix("+")))
    else:
        coeff.append(int(n))

print(coeff)
print(np.roots(coeff))

 -5x^3 +2x^2 -5x -1
[-1, 2, -1, -1]
[ 1.23278562+0.79255199j  1.23278562-0.79255199j -0.46557123+0.j        ]


### Task 10

numpy-ის საშუალებით იპოვეთ შემდეგი მრავალწევრის  x^2 + 4x - 5;  x^4 - 2x^3 + x^2 - 4x - 5. , როცა x=3, 9, 4.

In [118]:
x = [3, 9, 4]
p1 = np.poly1d([1, 4, -5])
p2 = np.poly1d([1, -2, 1, -4, -5])

for xi in x:
    print(f"x={xi}:")
    print(f"\tx^2 + 4x - 5 = {p1(xi)}")
    print(f"\tx^4 - 2x^3 + x^2 - 4x - 5 = {p2(xi)}")


x=3:
	x^2 + 4x - 5 = 16
	x^4 - 2x^3 + x^2 - 4x - 5 = 19
x=9:
	x^2 + 4x - 5 = 112
	x^4 - 2x^3 + x^2 - 4x - 5 = 5143
x=4:
	x^2 + 4x - 5 = 27
	x^4 - 2x^3 + x^2 - 4x - 5 = 123


### Task 11

numpy-ის საშუალებით იპოვეთ კლავიატურიდან შეტანილი სტრიქონის შესაბამისად მრავალწევრის მნიშვნელობები ასევე კლავიატურიდან შეტანილ რიცხვებში.

In [165]:
def get_coeff(equation: str) -> list:
    coeff = []
    for p in equation.split():
        n = p.split('x')[0]
        if n == '':
            coeff.append(1)
        elif n[0] == '-':
            if len(n) == 1:
                coeff.append(-1)
            else:
                coeff.append(int(n.removeprefix("-"))*-1)
        elif n[0] == '+':
            coeff.append(int(n.removeprefix("+")))
        else:
            coeff.append(int(n))
    return coeff


equation = input("Enter equation: ").replace(" ", "").strip()
equation = equation.replace("+", " +").replace("-", " -")

coeff = get_coeff(equation)
x = np.array(input("Enter points seperated by comma (ex. 1, 2, 3): ").split(', '), dtype=int)
p = np.poly1d(coeff)

for xi in x:
    print(f"x={xi}:")
    print(f"\t{equation}={p(xi)}")

x=1:
	 -2x^2 +5x -10=-7
x=2:
	 -2x^2 +5x -10=-8
x=3:
	 -2x^2 +5x -10=-13


### Task 12

numpy-ის საშუალებით იპოვეთ მატრიცის დეტერმინანტი 2, 3, 4, 5 განზომილების შემთხვევაში. 

In [187]:
d = [2, 3, 4, 5]
for di in d:
    m = np.random.randint(0, 20, size=(di, di))
    print("Matrix: ")
    print(m)
    print(f"Determinant: {np.linalg.det(m)}")

Matrix: 
[[11  8]
 [14  7]]
Determinant: -34.99999999999999
Matrix: 
[[ 7  7 13]
 [12  5  7]
 [16 11 12]]
Determinant: 333.0
Matrix: 
[[16  2 16 12]
 [16  3 13  8]
 [ 8  7 13 19]
 [19 15 13 15]]
Determinant: -9.999999999997808
Matrix: 
[[ 8  6  9 13 15]
 [11  6  4 17  0]
 [18  0  3  8  1]
 [ 4 15  6 19 18]
 [19 16  7  9 19]]
Determinant: -185282.00000000003


### Task 13

numpy-ის საშუალებით დაშალეთ 4x4-ზე მატრიცა ალგებრულ მინორებად. 

In [198]:
def minor_matrix(arr, i, j):
    return np.delete(np.delete(arr,i,axis=0), j, axis=1)


# m = np.random.randint(1, 10, size=(4, 4))
m = np.array([
    [8, 2, 1, 2],
    [4, 1, 3, 9],
    [9, 4, 7, 1],
    [5, 8, 4, 6]
])

for i in range(len(m)):
    for j in range(len(m[0])):
        print(i, j)
        print(minor_matrix(m, i, j))
        print()

0 0
[[1 3 9]
 [4 7 1]
 [8 4 6]]

0 1
[[4 3 9]
 [9 7 1]
 [5 4 6]]

0 2
[[4 1 9]
 [9 4 1]
 [5 8 6]]

0 3
[[4 1 3]
 [9 4 7]
 [5 8 4]]

1 0
[[2 1 2]
 [4 7 1]
 [8 4 6]]

1 1
[[8 1 2]
 [9 7 1]
 [5 4 6]]

1 2
[[8 2 2]
 [9 4 1]
 [5 8 6]]

1 3
[[8 2 1]
 [9 4 7]
 [5 8 4]]

2 0
[[2 1 2]
 [1 3 9]
 [8 4 6]]

2 1
[[8 1 2]
 [4 3 9]
 [5 4 6]]

2 2
[[8 2 2]
 [4 1 9]
 [5 8 6]]

2 3
[[8 2 1]
 [4 1 3]
 [5 8 4]]

3 0
[[2 1 2]
 [1 3 9]
 [4 7 1]]

3 1
[[8 1 2]
 [4 3 9]
 [9 7 1]]

3 2
[[8 2 2]
 [4 1 9]
 [9 4 1]]

3 3
[[8 2 1]
 [4 1 3]
 [9 4 7]]

